### ISSUE TITLE
Allow the player to swap between black/white in competitive mode

### ISSUE THREAD

**Issue by LausDaeus** [LausDaeus/GoProject#100]
Currently the player cannot swap colours (it is set to black) if they want to play as black/white against an AI.
![image](https://cloud.githubusercontent.com/assets/7795825/5926826/f8e85f18-a665-11e4-872a-2733cbbdde00.png)

**Comment by eilidhbagel** [comment]
Is competitive play mode -> swap player colour not working? Which situations exactly?

**Comment by LausDaeus** [comment]
Quick demo:

Start competitive mode:
![image](https://cloud.githubusercontent.com/assets/7795825/5930753/daf69c6a-a68b-11e4-8a07-bae33462d4fd.png)

Swap modes:
![image](https://cloud.githubusercontent.com/assets/7795825/5930754/e8b1c9ce-a68b-11e4-89ea-effc31bde83a.png)

Label still the same:
![image](https://cloud.githubusercontent.com/assets/7795825/5930783/64b03f56-a68c-11e4-8e49-11a6330b9372.png)

Sorry it does work now. The AI can grow a tidbit confused though if you swap colours mid-way. Generally some sort of feedback of the program acknowledging changes would be helpful.

**Comment by eilidhbagel** [comment]
Got the label updating now.
