### ISSUE TITLE
GUI delete stones does not update

### ISSUE THREAD

**Issue by LausDaeus** [LausDaeus/GoProject#101]
I was trying to delete a stone from the board via the GUI command CRTL-D (which is pretty useless as a menu-bar option given you can't select stones so maybe consider making it a toggleable mode) and the stone does not delete in spite of the user message indicating as much:
![image](https://cloud.githubusercontent.com/assets/7795825/5930887/c2a2c5e2-a68d-11e4-8c86-714265dcb219.png)

**Comment by eilidhbagel** [comment]
Wasn't deleting due to to the coordinate bug and was meant to be a toggle function... but I forgot to add the deselect part. All fixed.
