### ISSUE TITLE
Set/Remove Bounds

### ISSUE THREAD

**Issue by LausDaeus** [LausDaeus/GoProject#104]
This is similar to #103:
Simplify Set/Remove to one command such as "edit": 

![image](https://cloud.githubusercontent.com/assets/7795825/5931012/50296398-a68f-11e4-8d5a-f5d671aa6588.png)

As for the text box, it may be better to wait until #97 has been added.

**Comment by eilidhbagel** [comment]
Added bounds into single input dialog box with objective, leave open until bounds can have more than 1 set

**Comment by hoodscott** [comment]
Bounds now updated to "-"
