### ISSUE TITLE
Show coordinates next to board grid.

### ISSUE THREAD

**Issue by LausDaeus** [LausDaeus/GoProject#105]
Would be useful to show the coordinates to specify bounds/objective stones more easily. Here an example of what I mean:

![image](https://cloud.githubusercontent.com/assets/7795825/5967701/cca857de-a807-11e4-8b5e-77af8d6679e6.png)

As it's not very pretty, consider making it toggleable.

**Comment by hoodscott** [comment]
7ae92a239f5abe28b9371241ae31f4b4fe4c3279
