### ISSUE TITLE
Show file name on Window Heading

### ISSUE THREAD

**Issue by LausDaeus** [LausDaeus/GoProject#107]
Depending on the situation:
-If the problem is newly created show as "Untitled"
-If the problem was loaded use the file's name.
-If the problem was saved, update the name to that.

Here is the area intended for the name:
![image](https://cloud.githubusercontent.com/assets/7795825/5968288/d2a10f2c-a80d-11e4-855d-3d081566a6bf.png)

**Comment by hoodscott** [comment]
1f9ef77
