### ISSUE TITLE
Repaint board without moving the mouse

### ISSUE THREAD

**Issue by hoodscott** [LausDaeus/GoProject#109]
When making an AI move via the competitive menu or with Shift+m, the board does not update until the board is moused over, making the board repaint itself.  We can't simply call repaint inside the make AI move method because it is a static method and repaint is non-static, so we need to find some other way.

**Comment by eilidhbagel** [comment]
Changed AI move method to non-static, added repaint() and now call it through GraphicalUI.boardJP.GUIAIMove() non-statically instead
