### ISSUE TITLE
GUI: Draws the correct board after the Undo button is pressed

### ISSUE THREAD

**Issue by kirilhristov91** [LausDaeus/GoProject#111]
As you can see the AI is passing the correct coordinate of the move that should be made and nothing happens.
![1](https://cloud.githubusercontent.com/assets/9136023/5977739/65b9e732-a892-11e4-9d61-ccb8db2cd0a4.png)

I accidentally pressed the Undo button and the correct board from the above situation appeared.
![2](https://cloud.githubusercontent.com/assets/9136023/5977753/8eb506ee-a892-11e4-9d51-d6b0c589aeb3.png)

**Comment by LausDaeus** [comment]
I will check the GameEngine to see if the board representation is incorrect, but I would guess that this is a painting issue,

**Comment by eilidhbagel** [comment]
Was paint issue - fixed

**Comment by LausDaeus** [comment]
I tested the bug and it is still there. From what I could garner from the legalmovechecker it does add the board:
![image](https://cloud.githubusercontent.com/assets/7795825/5988925/af2d8650-a96c-11e4-89a5-66dc9663befc.png)

GUI board:
![image](https://cloud.githubusercontent.com/assets/7795825/5988926/bb07b16c-a96c-11e4-8b43-a1c7f9615235.png)

**Comment by LausDaeus** [comment]
This makes sense given it can restore the state with "undo".

**Comment by LausDaeus** [comment]
Although looking closely at this, it appears that 2 stones are placed for some very bizarre reason.

**Comment by LausDaeus** [comment]
Fixed. Alpha-Beta wasn't cloning the LegalMoveChecker properly.
