### ISSUE TITLE
Check the objective and the bounds when loading a board

### ISSUE THREAD

**Issue by hoodscott** [LausDaeus/GoProject#114]
When a board is loaded, make sure the objective makes sense for the current board.  Also make sure that the bounds are sensible.  Then we can set the setBounds() and setProblemSettings() to true in the gui.

**Comment by hoodscott** [comment]
Related to #96

**Comment by LausDaeus** [comment]
The loading from file does this in the Translator.java's  "translateToObjective" and "translateToSearchValues methods respectively.

**Comment by LausDaeus** [comment]
Objectives/Bounds inputted via the GUI (during run-time) can be checked, although one would have to pass them as a String.
