### ISSUE TITLE
"Save Problem" command saves file to project's root directory

### ISSUE THREAD

**Issue by LausDaeus** [LausDaeus/GoProject#118]
The save path is not configured correctly:
![image](https://cloud.githubusercontent.com/assets/7795825/6204344/d6c38726-b53f-11e4-94b3-98ccd20ea941.png)

**Comment by hoodscott** [comment]
Commented out FileIO method to append numbers on duplicate files.  Also, saves the directory so that the Save Problem button saves over the original file.  f8d3c41fc9bb2812a07b0dea60731d12b5fe7505
