### ISSUE TITLE
GUI: show coordinates spacing issue

### ISSUE THREAD

**Issue by LausDaeus** [LausDaeus/GoProject#119]
The coordinates are covered when stones are placed at the edge of the board:
![image](https://cloud.githubusercontent.com/assets/7795825/6220198/5d1a75e6-b62b-11e4-8268-7b8ec36617bd.png)

**Comment by hoodscott** [comment]
Coordinates moves closer to edge. 6f791080961e3a522f51e21915635cc73b1a5ece
