### ISSUE TITLE
GUI: cannot remove bounds.

### ISSUE THREAD

**Issue by LausDaeus** [LausDaeus/GoProject#120]
I was trying to solve the under the stones problem and cannot seem to remove the bounds by clicking on them in the mode after the objectives interface:
![image](https://cloud.githubusercontent.com/assets/7795825/6220303/cb7910dc-b62c-11e4-85c1-352acc42334c.png)

**Comment by hoodscott** [comment]
Clicking now toggles bounds.  https://github.com/LausDaeus/GoProject/commit/83dc8ec19a38d151ebf5e1c269a13870396c1db7
