### ISSUE TITLE
GUI: objective current not properly loaded

### ISSUE THREAD

**Issue by LausDaeus** [LausDaeus/GoProject#121]
I noticed this when trying to edit the objective/bounds it keeps partially resetting it:
![image](https://cloud.githubusercontent.com/assets/7795825/6220344/2b161aa8-b62d-11e4-808c-43041c52e827.png)

**Comment by hoodscott** [comment]
Now loads objective properly when editing.  37d3ca5f8707ec80bfa6aa5fcd29aa89f775f223
