### ISSUE TITLE
Enter problem creation when loading a board

### ISSUE THREAD

**Issue by hoodscott** [LausDaeus/GoProject#123]
When in competitive mode, when you load a board you are still in competitive mode even though you might not have selected bounds/objectives/players

**Comment by LausDaeus** [comment]
We could either:
1. Reject boards that don't have these requirements.
2. Disable the board loading.
3. Bring up the respective menus.

#2 would be easiest. With #3 you would have to load the board, check the objectives/bounds and also re-enquire as to who plays what colour. In regard of #1, the FileIO does throw an exception if the board does not have an objective, but bounds are treated as optional.

**Comment by LausDaeus** [comment]
Project has ended.
