### ISSUE TITLE
GUI fix scroll bar for Heuristics. 

### ISSUE THREAD

**Issue by LausDaeus** [LausDaeus/GoProject#129]
Not a major issue, but the dialog resizes based on the heuristic count and looks rather ugly as a result:
![image](https://cloud.githubusercontent.com/assets/7795825/6619973/d3dd494a-c8c5-11e4-84cb-734df30e2ffa.png)

**Comment by LausDaeus** [comment]
Just give it a fixed size to force it to be scrollable.

**Comment by eilidhbagel** [comment]
Doesn't really need a scroll bar - just changed the layout so the components aren't equal sizes, looks fine now
