### ISSUE TITLE
Refactor GraphicalGUI

### ISSUE THREAD

**Issue by LausDaeus** [LausDaeus/GoProject#58]
I'm looking at about 700 lines of code and numerous private classes. Please split these components up into multiple files, so it becomes easier to read.

**Comment by hoodscott** [comment]
All of the private action listener classes have been made into their own class.  Main class is now *only* ~500 lines.

Could still be abstracted further by having the components on the right hand side of the window in their own class but it would involve more getter/setters, static variables and time.
