### ISSUE TITLE
Update/Make hotkeys for GUI

### ISSUE THREAD

**Issue by LausDaeus** [LausDaeus/GoProject#88]
I was just trying to build a problem using the GUI builder. Are there any hotkeys to alternate between stone colours?

**Comment by eilidhbagel** [comment]
Set them just now as:
Problem Creation Mode:
Use black stones only - CTRL + B
Use white stones only - CTRL + W
Use both stones - SHIFT + Y
Delete stones - CTRL + D

Will add more later
