### ISSUE TITLE
Set default path for filebrowser in GUI

### ISSUE THREAD

**Issue by LausDaeus** [LausDaeus/GoProject#89]
It would be a lot faster to open problems if you made the file explorer point to the board path by default.

**Comment by hoodscott** [comment]
Works on my windows 8 pc with Eclipse, needs to be tested on other machines (and linux) to check it is fully working.

**Comment by LausDaeus** [comment]
Does not work for me. I checked the String in the FileMenuListener and got this:
"TeamProject\GoProject\saveData\boards". I think it is skipping over the "src" folder. Are you running the classes directly or building them?

**Comment by LausDaeus** [comment]
I am guessing this relates to my IDE's "special" setup. I'll add a small hotfix.

**Comment by hoodscott** [comment]
Hotfix introduced a bug to Eclipse linux builds.  I have made a change to fix it, but we just need to test it again.

**Comment by LausDaeus** [comment]
Works.
