### ISSUE TITLE
Implement Basic Alpha-Beta

### ISSUE THREAD

**Issue by LausDaeus** [LausDaeus/GoProject#92]
Already done. Check if it works.

**Comment by LausDaeus** [comment]
Can you please optimise the alpha-beta so it does not generate all moves/boards in advance, but rather in the loop and then uses them. This was also a major memory issue with the minimax that had to be fixed.

**Comment by LausDaeus** [comment]
Further, please import the Actions enum from the Objective, as it is much more efficient than equating a String each time. If you want an example/guideline, I have adjusted the minimax for this.

**Comment by kirilhristov91** [comment]
It seems to work now. Needs further testing though.
