### ISSUE TITLE
Capturing Bug

### ISSUE THREAD

**Issue by hoodscott** [LausDaeus/GoProject#93]
In AITestA, when you put two white stones into the black eye, then neither group is captured even though they both have zero liberties.
![screenshot-](https://cloud.githubusercontent.com/assets/9320749/5916711/f61a4c88-a60b-11e4-8049-ac1012ed5f1e.png)
![screenshot- -1](https://cloud.githubusercontent.com/assets/9320749/5916712/f7f01cf4-a60b-11e4-9b5f-0a662eeaf7fb.png)

**Comment by LausDaeus** [comment]
No more rectangular boards. Set requirement to ensure dimensions are equal.

**Comment by LausDaeus** [comment]
I have modified Translator.java to throw an Exception when read in boards do not have a matching height and width.
