### ISSUE TITLE
Bounds will not show on GUI when the box is too small

### ISSUE THREAD

**Issue by LausDaeus** [LausDaeus/GoProject#99]
Bounds will not show if either the height or width of the bounded area = 1:

On GUI:
![image](https://cloud.githubusercontent.com/assets/7795825/5926727/35671066-a665-11e4-83dc-73acc02cc146.png)

Loaded board:
![image](https://cloud.githubusercontent.com/assets/7795825/5926735/4853f61c-a665-11e4-87f2-af375883f001.png)

 Maybe you want to shift them a little so they do not sit on the intersections or try another approach. Also try to make the code flexible enough to easily adapt to (#97).

**Comment by eilidhbagel** [comment]
![image](https://cloud.githubusercontent.com/assets/9320722/5927870/d6913c8e-a66d-11e4-8a2d-4ffccbcc827f.png)

Changed to this for now - leave open until I test it a bit more.
